Description: >
  Project: Udacity Cloud DevOps Nanodegree exercise: 
  Promote to Production, Lesson 4: 27, 28 and 29 
  Author: Udacity team
  This CloudFormation template creates a S3 bucket


Parameters:
  BUCKET_NAME:
    Description: The name of the bucket
    Type: String


Resources:

WebsiteBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub "${BUCKET_NAME}"
    AccessControl: PublicRead
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: 404.html

WebsiteBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref 'WebsiteBucket'
    PolicyDocument:
      Statement:
      - Sid: PublicReadForGetBucketObjects
        Effect: Allow
        Principal: '*'
        Action: s3:GetObject
        Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

